### ISSUE TITLE
Feature Request: Carrier List Services

### ISSUE THREAD

**Issue by axlekb** [Jellyfishboy/shipstation#10]
Hello! 

Thanks so much for this gem!

I noticed that this endpoint has not been included:
https://www.shipstation.com/developer-api/#/reference/carriers/list-services/list-services

Since it's a bit irregular (nested), I was also wondering how you might implement it.

**Comment by Jellyfishboy** [comment]
Hey @axlekb I have added the new endpoint. Please check the documentation and updated the gem to version `0.17.7`. Thanks :)
