### ISSUE TITLE
TypeError: no implicit conversion of Symbol into Integer on bulk order update call

### ISSUE THREAD

**Issue by iyerushalmi** [Jellyfishboy/shipstation#3]
Hello, I was trying to run a bulk update on orders as follows:

```
orders = Shipstation.request(:get, "orders/listbytag", {"orderStatus" => "awaiting_shipment", "tagId" => 54600})["orders"]
response = Shipstation.request(:post, "orders/createorders", orders)
```

I simply tried spitting back the same order data back to the server without making any modifications, but i received the following error:

> TypeError: no implicit conversion of Symbol into Integer
> 	from /Users/username/.rvm/gems/ruby-2.2.5/gems/shipstation-0.12.3/lib/shipstation.rb:43:in `[]'
> 	from /Users/username/.rvm/gems/ruby-2.2.5/gems/shipstation-0.12.3/lib/shipstation.rb:43:in `request'
> 	from /Users/username/Documents/OLD MACBOOK FILES/username/Rails/app_folder/lib/shipstation_integrator.rb:114:in `remove_tag_from_all_orders'
> 	from (irb):2
> 	from /Users/username/.rvm/gems/ruby-2.2.5/gems/railties-4.1.4/lib/rails/commands/console.rb:90:in `start'
> 	from /Users/username/.rvm/gems/ruby-2.2.5/gems/railties-4.1.4/lib/rails/commands/console.rb:9:in `start'
> 	from /Users/username/.rvm/gems/ruby-2.2.5/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:69:in `console'
> 	from /Users/username/.rvm/gems/ruby-2.2.5/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
> 	from /Users/username/.rvm/gems/ruby-2.2.5/gems/railties-4.1.4/lib/rails/commands.rb:17:in `<top (required)>'
> 	from bin/rails:4:in `require'
> 	from bin/rails:4:in `<main>'

I digged around but couldn't figure out the issue. Any ideas?

**Comment by Jellyfishboy** [comment]
@iyerushalmi The above error would indicate the format of your params in the POST request is not correct for the ShipStation API. Please send a code example of the value of of your `orders` variable.

**Comment by Jellyfishboy** [comment]
@iyerushalmi the stack trace points to this line in the shipstation lib class: https://github.com/Jellyfishboy/shipstation/blob/master/lib/shipstation.rb#L43

How are you setting your username and password authentication details?

**Comment by Jellyfishboy** [comment]
Closing due to no response. Please make sure you update your gem to the latest version to access all features.
