### ISSUE TITLE
Order delete, undefined method

### ISSUE THREAD

**Issue by keithbooher** [Jellyfishboy/shipstation#5]
Been using this gem mostly no problem so far, but I'm getting unexpected behavior from:

Shipstation::Order.delete(s.order_number)

The delete method is undefined for some reason.
error tells me what im telling you

undefined method `delete' for Shipstation::Order:Class Did you mean? delegate

**Comment by Jellyfishboy** [comment]
Hey @keithbooher can you please send me a copy of your `Gemfile.lock` file. Thanks.

**Comment by Jellyfishboy** [comment]
Closing due to no response. Please make sure you update your gem to the latest version to access all features.
